Repository neo4j/neo4j-java-driver, pull requests merged in 2020-07, with the labels that each got.

#745 Bump Netty to 4.1.51-Final
  pom.xml
Labels: dependencies

#743 Fix native compilation with Netty 4.1.50 on GraalVM.
  driver/src/main/java/org/neo4j/driver/internal/svm/NettySubstitutions.java
  driver/src/main/resources/META-INF/native-image/org.neo4j.driver/neo4j-java-driver/reflection-config.json
Labels: bug, cherry-picked

#747 Bump Netty to 4.1.51-Final (#745)
  pom.xml
Labels: cherry-picked

#749 4.0 add retries for cluster overview test (#748)
  driver/src/test/java/org/neo4j/driver/util/cc/Cluster.java
Labels: cherry-picked
